export enum TECH_STATUS_CODE {
    PROVISIONAL_OVER_CURRENT = 'PROVISIONAL, CURRENT',
    PROVISIONAL = 'PROVISIONAL',
    CURRENT = 'CURRENT',
    ARCHIVE = 'ARCHIVE',
    ALL = 'PROVISIONAL, CURRENT, ARCHIVE'
}